### PR TITLE
migrated class to hooks

### PR DESCRIPTION
**Pull request by shmiitg**
Sir I have changed the following files from using class based components to functional components.
calender.js
codestudio.js
menubar.js
minesweeper
markdown_editor.js
markdown_reader.js
pdf.js
processmanager.js

You can verify and merge. Gradually I will change all the files

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello @shmiitg thanks for the PR, could you please remove the old code instead of commenting. That would make the pr readable. Does this break any changes?

**Comment by shmiitg** [comment]
> Hello @shmiitg thanks for the PR, could you please remove the old code instead of commenting. That would make the pr readable. Does this break any changes?

Ok I am removing it...It won't cause any problems.

**Comment by shmiitg** [comment]
Done sir. You can check now

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
> Done sir. You can check now

Thank you will review it asap

**Comment by shmiitg** [comment]
@RAJAGOPALAN-GANGADHARAN any updates?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@shmiitg can you please review the comments I left out?

**Comment by shmiitg** [comment]
> @shmiitg can you please review the comments I left out?

Sorry I didn't get which comments you are talking about? Please elaborate

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
> > @shmiitg can you please review the comments I left out?
> 
> 
> 
> Sorry I didn't get which comments you are talking about? Please elaborate

I have left some inline comments are you not able to see it?

**Comment by shmiitg** [comment]
> > > @shmiitg can you please review the comments I left out?
> > 
> > 
> > Sorry I didn't get which comments you are talking about? Please elaborate
> 
> I have left some inline comments are you not able to see it?

Yaah I saw them. Should I uncomment some of them or remove them? Please tell

**Comment by shmiitg** [comment]
While changing classes to hooks, I have kept all those comments and not removed any

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
image

This is what I meant by inline comments, Github allows us to review each line and directly specify comment. Please check that, thanks

**Review by shmiitg — COMMENTED** [review]
Component can be remove from imports ( I forgot to remove it)

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
FYI I have left more comments like this. Please check that as well

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@shmiitg thank you for this PR, even though it is not merged I have granted you 15 points in the leaderboard.

**Comment by shmiitg** [comment]
> @shmiitg thank you for this PR, even though it is not merged I have granted you 15 points in the leaderboard.

Thank you sir

**Pull request closed without merging**
