### PR TITLE
update

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hello @akshatmittal2002 Is there an issue attached to this PR? If not can you create one(so that I can assign extra points for you) Thanks

**Comment by akshatmittal2002** [comment]
>

**Comment by akshatmittal2002** [comment]
> Hello @akshatmittal2002 Is there an issue attached to this PR? If not can you create one(so that I can assign extra points for you) Thanks

There were some errors in readme file. I have resolved those.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@akshatmittal2002 I understand but can you create an issue here stating the problem here - https://github.com/RAJAGOPALAN-GANGADHARAN/JS-OS/issues . Thanks!

**Pull request closed without merging**
