### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**
Issue [link](https://github.com/RAJAGOPALAN-GANGADHARAN/JS-OS/issues/27)

Removed Packages : 

```
Unused dependencies
* @babel/runtime
* @fortawesome/fontawesome-svg-core
* @fortawesome/free-solid-svg-icons
* @fortawesome/react-fontawesome
* @monaco-editor/react
* @react-pdf/renderer
* argparse
* glot-api
* html-to-react
* i
* jquery
* monaco-editor
* npm
* pdf-viewer-reactjs
* react-ace
* react-calendar
* react-fontawesome
* react-froala-wysiwyg
* react-items-carousel
* react-pdf
* react-read-pdf
* react-responsive-carousel
*** react-router
* react-scripts
* react-slideshow-image
* react-spreadsheet
* react-trumbowyg
* react-viewer
Unused devDependencies
* gh-pages
* react-app-rewired
Missing dependencies
* regenerator-runtime: .\src\index.js
* ace: .\src\defaultapps\texteditor\src\ext-emmet.js
* @tinymce/tinymce-react: .\src\defaultapps\markdown\markdown_editor.js
* prop-types: .\src\defaultapps\blogfeed\components\CodeBlock.js
```

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ArchismanKarmakar , Thank you for this PR. Are you sure it doesn't break any changes? I will also test this locally once - this weekend(pardon my delay, work related things)

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar , Thank you for this PR. Are you sure it doesn't break any changes? I will also test this locally once - this weekend(pardon my delay, work related things)

Yes pretty bit. You can also try it. You can use [DPCHECK](https://www.npmjs.com/package/depcheck)

From the beginning only I was not able to start the server by npm start it showed some error, but the error was due to a package called three, three was throwing error so I couldn't compile & check.

It's okay when you're busy everything goes out of mind, we can't do anything except just following our routine. - please don't mind for this, irrespective of my age I am telling it you sorry sir.

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar , Thank you for this PR. Are you sure it doesn't break any changes? I will also test this locally once - this weekend(pardon my delay, work related things)

i am not able to run it because the packages are outdated and npm i is giving error at react now. Can you please provide your node_modules folder please

**Comment by ArchismanKarmakar** [comment]
I fixed everything now it's running in my machine also. few node_modules were causing error. updating package & package lock now

**Comment by ArchismanKarmakar** [comment]
i kept few unused packages because after removing them npm is throwing error

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ArchismanKarmakar Thanks for the update, can you please remove package-lock.json from this commit? Ive been meaning to remove that from repository, Once deleted could you please add that to gitignore as well

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar Thanks for the update, can you please remove package-lock.json from this commit? Ive been meaning to remove that from repository, Once deleted could you please add that to gitignore as well

check now sir

**Comment by ArchismanKarmakar** [comment]
> @ArchismanKarmakar Thanks for the update, can you please remove package-lock.json from this commit? Ive been meaning to remove that from repository, Once deleted could you please add that to gitignore as well

#27 issue solved

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Moved to #48

**Pull request closed without merging**
